# docker-compose.yml
version: "3.8"
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./src/helloworld:/usr/local/apache2/htdocs/helloworld
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src/helloworld:/usr/local/apache2/htdocs/helloworld
    working_dir: /usr/local/apache2/htdocs/helloworld
  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/helloworld:/usr/local/apache2/htdocs/helloworld
    working_dir: /usr/local/apache2/htdocs/helloworld
    command: install