# docker-compose.yml
version: "3.8"
services:
  apache_service:
    container_name: apache_container
    build: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    depends_on:
      - php_service
  php_service:
    container_name: php_container
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
